# AWS buidlspec version
version: 0.2

phases:
  install:
    commands:
      - bash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
      - npm install
  build:
    commands:
      - npm run build
      - echo "Finished build"

artifacts:
  files:
    - dist/home-app/*
  name: CODEBUILD_GIT_BRANCH
